services:
  - type: web
    name: cliente-service
    env: java
    plan: free
    rootDir: cliente-service
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/cliente-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: default
