services:
  - type: web
    name: cliente-service
    env: java
    plan: free
    region: oregon
    branch: develop
    rootDir: cliente-service
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/cliente-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://tu-host-mysql:3306/ecomarket_db
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: JWT_SECRET
        value: mi_clave_secreta_super_segura_1234567890
